package shop.frankit.common.error

enum class ErrorCode {
    NOT_FOUND__USER,
    NOT_FOUND__PRODUCT,
    NOT_FOUND__PRODUCT_OPTION,
    NOT_FOUND__PRODUCT_OPTION_ATTRIBUTE,

    FAILED_LOGIN,
    FAILED_SIGN_UP__DUPLICATED_EMAIL,

    FAILED_UPDATE_PRODUCT__NOT_OWNER,

    TOO_MANY__PRODUCT_OPTION,
    TOO_MANY__PRODUCT_OPTION_ATTRIBUTE,

    CONFLICT__PRODUCT_OPTION_NAME,
    CONFLICT__OPTION_ATTRIBUTE_NAME,

    OPTION_ATTRIBUTE_MISSING,

    NOT_MATCH__PRODUCT_OPTION,

    INVALID_REQUEST__AUTH_TOKEN,
    INVALID_REQUEST__AUTH_ID,
    UNKNOWN_ERROR,

    REQUEST_DATA_ERROR,
    SERVER_ERROR
}